name: analysis
channels: 
 - conda-forge
#  - intel
dependencies:
 - python=3.12
 - pip
 - setuptools
 - notebook
 - jupyterlab
 - numpy
 - xarray
 - pandas
 - matplotlib
 - seaborn
 - scikit-learn
 - scipy
 - statsmodels
 - matplotlib
 - h5py
 - scikit-image
 - imageio
 - imageio-ffmpeg
#  - oasis-deconv
 - numba # optional, motion utils, also pandas performance
#  - mkl_fft # optional, motion utils
 - numexpr # pandas performance
 - bottleneck # pandas performance
 - pytables # pandas performance
 - pyarrow # pandas IO
 - zlib # pandas IO
 - pyyaml
 - pytest
 - tqdm
 - tifffile
 - python-dotenv
 - jax
 - ocl-icd-system # unsure why?
#  - seaborn-image
#  - xmovie
 - altair-all
 - pip:
   - scanimage-tiff-reader
  #  - jax[cpu]
