name: analysis
channels: 
 - conda-forge
 - intel
dependencies:
 - python
 - pip
 - setuptools
 - notebook
 - jupyterlab
 - numpy
 - xarray
 - pandas
 - matplotlib
 - seaborn
 - scikit-learn
 - scipy
 - statsmodels
 - matplotlib
 - h5py
 - scikit-image
 - imageio
 - imageio-ffmpeg
 - oasis-deconv
 - numba # optional, motion utils
 - mkl_fft # optional, motion utils
 - numexpr # pandas performance
 - bottleneck # pandas performance
 - pytables # pandas performance
 - pyarrow # pandas IO
 - zlib # pandas IO
 - pyyaml
 - pytest
 - tqdm
 - tifffile
 - python-dotenv
 - pip:
   - scanimage-tiff-reader
   - jax[cpu]
