name: analysis
channels: 
 - conda-forge
 - intel
dependencies:
 - python
 - pip
 - notebook
 - jupyterlab
 - numpy
 - xarray
 - pandas
 - matplotlib
 - seaborn
 - scikit-learn
 - scipy
 - statsmodels
 - matplotlib
 - h5py
 - scikit-image
 - imageio
 - imageio-ffmpeg
 - cython
 - cvxpy
 - numba # optional, motion utils
 - mkl_fft # optional, motion utils
 - numexpr # pandas performance
 - bottleneck # pandas performance
 - pytables # pandas performance
 - pyarrow # pandas IO
 - zlib # pandas IO
 - pip:
   - pytest
   - scanimage-tiff-reader
   - tqdm
   - tifffile
   - pyqt5
   - jax[cpu]
   - git+https://github.com/j-friedrich/OASIS